sonar.organization=andreferraro
sonar.projectKey=andreferraro_foxcape
sonar.projectName=foxcape

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
