sonar.organization=andreferraro
sonar.projectKey=andreferraro_foxcape
sonar.projectName=foxcape

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10,3.11,3.12,3.13
